### ISSUE TITLE
Skyblock Prices

### ISSUE THREAD

**Issue by Tumeden** [optimusprime338/PrimeGamesIssueReport#14]
- All FENCES: 32 : 250 
- All GATES: 32 : 200
- iron bars: 16:325
- all Stained:32:350
- Glass pane:32:300
- all stained plane:32:300
- Jack o Lantern: 16 :300
- Glowstone:32:300
- sea lantern:32:300
- redstone lamp:32:350
- torch: 32 : 200
- redstone torch: 32 : 300
- flin and steel: 5 : 200
- terracotta (all) : 32 : 300
- glazed (all): 32 : 400
- obsidian: 2 : 700
- soul sand: 32 : 800
- all slabs: 32 : 200
- Jump Boost: 1 : 8 mins  : 800$
- Jump Boost: 2 : 8 mins  : 1500$
- speed: 1 : 8 mins  : 800$
- fire resistence: 8 mins  : 1000
- regen: 1 : 5 mins  : 2000
- regen: 2: 5 mins  : 800$
- strength: 1 : 5 mins  : 2500$
- strength: 2: 5 min: 5000$
- nightvision: 8 mins : 1500$
- haste: 2: 8 mins : 2500$
- packed ice: 16 : 500
- snow: 32: 500

**Comment by Sacred-Lotus** [comment]
Skyblock Prices (mid floor)

- All FENCES: 32 : 250 
All GATES: 32 : 200
iron bars: 16:325
all Stained:32:350
Glass pane:32:300
all stained plane:32:300
Jack o Lantern: 16 :300
Glowstone:32:300
sea lantern:32:300
redstone lamp:32:350
torch: 32 : 200
redstone torch: 32 : 300
flin and steel: 5 : 200
terracotta (all) : 32 : 300
glazed (all): 32 : 400
obsidian: 2 : 700
soul sand: 32 : 800
all slabs: 32 : 200
Jump Boost: 1 : 8 mins  : 800$
Jump Boost: 2 : 8 mins  : 1500$
speed: 1 : 8 mins  : 800$
fire resistence: 8 mins  : 1000
regen: 1 : 5 mins  : 2000
regen: 2: 5 mins  : 800$
Strenght: 1 : 5 mins  : 2500$
strenght: 2: 5 min: 5000$
nightvision: 8 mins : 1500$
haste: 2: 8 mins : 2500$
packed ice: 16 : 500
snow: 32: 500
