### ISSUE TITLE
Skyblock shop Issues

### ISSUE THREAD

**Issue by Tumeden** [optimusprime338/PrimeGamesIssueReport#4]
Many people complaining about  Skyblock lag,  as well as people Block glitching to go mine the blocks in the flat land... needs to be fixed.  

Maybe generate a void world (or copys someone skyblock world)  and put a /warp shop there,  would solve mining block issues.

**Comment by optimusprime338** [comment]
@Tumeden  please generate void all around as well as set hidden block(ID = 95) all around!
